"""Communication and messaging tools catalog."""

COMMUNICATION_TOOLS = [
    {
        "id": "slack",
        "name": "Slack",
        "description": "Send messages and manage Slack channels",
        "category": "communication",
        "provider": "slack",
        "icon": "💬",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "discord",
        "name": "Discord",
        "description": "Send messages to Discord channels",
        "category": "communication",
        "provider": "discord",
        "icon": "🎮",
        "requires_auth": True,
        "auth_type": "webhook",
    },
    {
        "id": "telegram",
        "name": "Telegram",
        "description": "Send messages via Telegram bot",
        "category": "communication",
        "provider": "telegram",
        "icon": "✈️",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "gmail",
        "name": "Gmail",
        "description": "Send and read Gmail emails",
        "category": "communication",
        "provider": "google",
        "icon": "📧",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "outlook",
        "name": "Outlook",
        "description": "Send and read Outlook emails",
        "category": "communication",
        "provider": "microsoft",
        "icon": "📨",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "sendgrid",
        "name": "SendGrid",
        "description": "Send emails via SendGrid API",
        "category": "communication",
        "provider": "sendgrid",
        "icon": "📬",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "twilio",
        "name": "Twilio",
        "description": "Send SMS and make calls via Twilio",
        "category": "communication",
        "provider": "twilio",
        "icon": "📱",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "zoom",
        "name": "Zoom",
        "description": "Create and manage Zoom meetings",
        "category": "communication",
        "provider": "zoom",
        "icon": "🎥",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
]
