"""Data and database tools catalog."""

DATA_TOOLS = [
    {
        "id": "postgresql",
        "name": "PostgreSQL",
        "description": "Query and manage PostgreSQL databases",
        "category": "data",
        "provider": "postgresql",
        "icon": "🐘",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "mysql",
        "name": "MySQL",
        "description": "Query and manage MySQL databases",
        "category": "data",
        "provider": "mysql",
        "icon": "🐬",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "mongodb",
        "name": "MongoDB",
        "description": "Query and manage MongoDB databases",
        "category": "data",
        "provider": "mongodb",
        "icon": "🍃",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "redis",
        "name": "Redis",
        "description": "Interact with Redis cache",
        "category": "data",
        "provider": "redis",
        "icon": "🔴",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "elasticsearch",
        "name": "Elasticsearch",
        "description": "Search and analyze data in Elasticsearch",
        "category": "data",
        "provider": "elasticsearch",
        "icon": "🔎",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "snowflake",
        "name": "Snowflake",
        "description": "Query Snowflake data warehouse",
        "category": "data",
        "provider": "snowflake",
        "icon": "❄️",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "bigquery",
        "name": "BigQuery",
        "description": "Query Google BigQuery datasets",
        "category": "data",
        "provider": "google",
        "icon": "📊",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "supabase",
        "name": "Supabase",
        "description": "Interact with Supabase database and storage",
        "category": "data",
        "provider": "supabase",
        "icon": "⚡",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "firebase",
        "name": "Firebase",
        "description": "Access Firebase Firestore and Realtime Database",
        "category": "data",
        "provider": "firebase",
        "icon": "🔥",
        "requires_auth": True,
        "auth_type": "api_key",
    },
]
