"""Developer and DevOps tools catalog."""

DEVELOPER_TOOLS = [
    {
        "id": "github",
        "name": "GitHub",
        "description": "Manage GitHub repositories, issues, and pull requests",
        "category": "developer",
        "provider": "github",
        "icon": "🐙",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "gitlab",
        "name": "GitLab",
        "description": "Manage GitLab projects and pipelines",
        "category": "developer",
        "provider": "gitlab",
        "icon": "🦊",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "bitbucket",
        "name": "Bitbucket",
        "description": "Manage Bitbucket repositories",
        "category": "developer",
        "provider": "bitbucket",
        "icon": "🪣",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "jira",
        "name": "Jira",
        "description": "Manage Jira issues and projects",
        "category": "developer",
        "provider": "atlassian",
        "icon": "📋",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "linear",
        "name": "Linear",
        "description": "Manage Linear issues and projects",
        "category": "developer",
        "provider": "linear",
        "icon": "📐",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "vercel",
        "name": "Vercel",
        "description": "Deploy and manage Vercel projects",
        "category": "developer",
        "provider": "vercel",
        "icon": "▲",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "netlify",
        "name": "Netlify",
        "description": "Deploy and manage Netlify sites",
        "category": "developer",
        "provider": "netlify",
        "icon": "🌐",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "aws",
        "name": "AWS",
        "description": "Interact with AWS services",
        "category": "developer",
        "provider": "aws",
        "icon": "☁️",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "docker",
        "name": "Docker",
        "description": "Manage Docker containers and images",
        "category": "developer",
        "provider": "docker",
        "icon": "🐳",
        "requires_auth": False,
    },
    {
        "id": "kubernetes",
        "name": "Kubernetes",
        "description": "Manage Kubernetes clusters and resources",
        "category": "developer",
        "provider": "kubernetes",
        "icon": "☸️",
        "requires_auth": True,
        "auth_type": "credentials",
    },
    {
        "id": "stripe",
        "name": "Stripe",
        "description": "Process payments and manage Stripe data",
        "category": "developer",
        "provider": "stripe",
        "icon": "💳",
        "requires_auth": True,
        "auth_type": "api_key",
    },
]
