"""Productivity and collaboration tools catalog."""

PRODUCTIVITY_TOOLS = [
    {
        "id": "notion",
        "name": "Notion",
        "description": "Create, read, and update Notion pages and databases",
        "category": "productivity",
        "provider": "notion",
        "icon": "📝",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "google_docs",
        "name": "Google Docs",
        "description": "Create and edit Google Docs documents",
        "category": "productivity",
        "provider": "google",
        "icon": "📄",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "google_sheets",
        "name": "Google Sheets",
        "description": "Create and manipulate Google Sheets spreadsheets",
        "category": "productivity",
        "provider": "google",
        "icon": "📊",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "google_drive",
        "name": "Google Drive",
        "description": "Access and manage files in Google Drive",
        "category": "productivity",
        "provider": "google",
        "icon": "💾",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "airtable",
        "name": "Airtable",
        "description": "Manage Airtable bases and records",
        "category": "productivity",
        "provider": "airtable",
        "icon": "🗂️",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "trello",
        "name": "Trello",
        "description": "Manage Trello boards, lists, and cards",
        "category": "productivity",
        "provider": "trello",
        "icon": "📋",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "asana",
        "name": "Asana",
        "description": "Manage Asana projects and tasks",
        "category": "productivity",
        "provider": "asana",
        "icon": "✅",
        "requires_auth": True,
        "auth_type": "oauth2",
    },
    {
        "id": "monday",
        "name": "Monday.com",
        "description": "Manage Monday.com boards and items",
        "category": "productivity",
        "provider": "monday",
        "icon": "📅",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "clickup",
        "name": "ClickUp",
        "description": "Manage ClickUp tasks and projects",
        "category": "productivity",
        "provider": "clickup",
        "icon": "🎯",
        "requires_auth": True,
        "auth_type": "api_key",
    },
]
