"""Search and information retrieval tools catalog."""

SEARCH_TOOLS = [
    {
        "id": "google_search",
        "name": "Google Search",
        "description": "Search the web using Google",
        "category": "search",
        "provider": "google",
        "icon": "🔍",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "bing_search",
        "name": "Bing Search",
        "description": "Search the web using Microsoft Bing",
        "category": "search",
        "provider": "microsoft",
        "icon": "🔎",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "duckduckgo",
        "name": "DuckDuckGo",
        "description": "Privacy-focused web search",
        "category": "search",
        "provider": "duckduckgo",
        "icon": "🦆",
        "requires_auth": False,
    },
    {
        "id": "tavily_search",
        "name": "Tavily Search",
        "description": "AI-powered search optimized for LLMs",
        "category": "search",
        "provider": "tavily",
        "icon": "🎯",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "serper",
        "name": "Serper",
        "description": "Google Search API for developers",
        "category": "search",
        "provider": "serper",
        "icon": "🌐",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "exa_search",
        "name": "Exa Search",
        "description": "Neural search engine for finding similar content",
        "category": "search",
        "provider": "exa",
        "icon": "🧲",
        "requires_auth": True,
        "auth_type": "api_key",
    },
    {
        "id": "wikipedia",
        "name": "Wikipedia",
        "description": "Search and retrieve Wikipedia articles",
        "category": "search",
        "provider": "wikipedia",
        "icon": "📚",
        "requires_auth": False,
    },
    {
        "id": "arxiv",
        "name": "arXiv",
        "description": "Search academic papers on arXiv",
        "category": "search",
        "provider": "arxiv",
        "icon": "📄",
        "requires_auth": False,
    },
    {
        "id": "youtube_search",
        "name": "YouTube Search",
        "description": "Search YouTube videos",
        "category": "search",
        "provider": "youtube",
        "icon": "📺",
        "requires_auth": True,
        "auth_type": "api_key",
    },
]
