@echo off
REM Setup script for local network access (Windows)

echo ========================================
echo AgenticBuilder - Local Network Setup
echo ========================================
echo.

REM Get local IP address
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set IP=%%a
    goto :found
)

:found
REM Trim spaces
set IP=%IP: =%

echo Your local IP address: %IP%
echo.

REM Create frontend .env.local
echo Creating frontend/.env.local...
echo # Auto-generated by setup-local-network.bat > frontend\.env.local
echo NEXT_PUBLIC_API_URL=http://%IP%:8000 >> frontend\.env.local
echo.

echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo Frontend will be accessible at:
echo   http://%IP%:3000
echo.
echo Backend will be accessible at:
echo   http://%IP%:8000
echo.
echo From other devices on the same network:
echo   1. Connect to the same WiFi
echo   2. Open browser and go to: http://%IP%:3000
echo.
echo To start the services:
echo   1. Backend:  cd backend ^&^& python main.py
echo   2. Frontend: cd frontend ^&^& npm run dev
echo.
echo Press any key to exit...
pause >nul
