#!/bin/bash
# Setup script for local network access (Mac/Linux)

echo "========================================"
echo "AgenticBuilder - Local Network Setup"
echo "========================================"
echo ""

# Get local IP address
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)
else
    # Linux
    IP=$(hostname -I | awk '{print $1}')
fi

if [ -z "$IP" ]; then
    echo "❌ Could not detect local IP address"
    echo "Please run 'ifconfig' or 'ip addr' to find your IP manually"
    exit 1
fi

echo "Your local IP address: $IP"
echo ""

# Create frontend .env.local
echo "Creating frontend/.env.local..."
cat > frontend/.env.local << EOF
# Auto-generated by setup-local-network.sh
NEXT_PUBLIC_API_URL=http://$IP:8000
EOF

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Frontend will be accessible at:"
echo "  http://$IP:3000"
echo ""
echo "Backend will be accessible at:"
echo "  http://$IP:8000"
echo ""
echo "From other devices on the same network:"
echo "  1. Connect to the same WiFi"
echo "  2. Open browser and go to: http://$IP:3000"
echo ""
echo "To start the services:"
echo "  1. Backend:  cd backend && python main.py"
echo "  2. Frontend: cd frontend && npm run dev"
echo ""
