"""add_trigger_execution_model

Revision ID: 6fd293ea7a48
Revises: 7c55ca2b841e
Create Date: 2025-11-16 15:21:08.655113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fd293ea7a48'
down_revision: Union[str, None] = '7c55ca2b841e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('service_display_name', sa.String(length=200), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_name', name='uq_user_service_api_key')
    )
    op.create_index('ix_user_api_keys_active', 'user_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_index('ix_user_api_keys_user_service', 'user_api_keys', ['user_id', 'service_name'], unique=False)
    op.create_table('trigger_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_id', sa.String(length=255), nullable=True),
    sa.Column('trigger_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_executions_status'), 'trigger_executions', ['status'], unique=False)
    op.create_index('ix_trigger_executions_status_time', 'trigger_executions', ['status', 'triggered_at'], unique=False)
    op.create_index('ix_trigger_executions_trigger', 'trigger_executions', ['trigger_type', 'trigger_id'], unique=False)
    op.create_index(op.f('ix_trigger_executions_trigger_id'), 'trigger_executions', ['trigger_id'], unique=False)
    op.create_index(op.f('ix_trigger_executions_trigger_type'), 'trigger_executions', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_trigger_executions_triggered_at'), 'trigger_executions', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_trigger_executions_workflow_id'), 'trigger_executions', ['workflow_id'], unique=False)
    op.create_index('ix_trigger_executions_workflow_time', 'trigger_executions', ['workflow_id', 'triggered_at'], unique=False)
    # Drop custom_tool_ratings first (has FK to custom_tools)
    op.drop_index('idx_custom_tool_ratings_tool_id', table_name='custom_tool_ratings')
    op.drop_index('idx_custom_tool_ratings_user_id', table_name='custom_tool_ratings')
    op.drop_table('custom_tool_ratings')
    
    # Drop custom_tool_usage (has FK to custom_tools)
    op.drop_index('idx_custom_tool_usage_executed_at', table_name='custom_tool_usage')
    op.drop_index('idx_custom_tool_usage_tool_id', table_name='custom_tool_usage')
    op.drop_index('idx_custom_tool_usage_user_id', table_name='custom_tool_usage')
    op.drop_table('custom_tool_usage')
    
    # Finally drop custom_tools
    op.drop_index('idx_custom_tools_category', table_name='custom_tools')
    op.drop_index('idx_custom_tools_marketplace', table_name='custom_tools')
    op.drop_index('idx_custom_tools_public', table_name='custom_tools')
    op.drop_index('idx_custom_tools_user_id', table_name='custom_tools')
    op.drop_table('custom_tools')
    op.alter_column('agent_blocks', 'sub_blocks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_blocks', 'inputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_blocks', 'outputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index('ix_agent_blocks_config_gin', table_name='agent_blocks', postgresql_using='gin')
    op.alter_column('agent_executions', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_executions', 'output_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_executions', 'execution_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_agent_exec_session_status', table_name='agent_executions')
    op.drop_index('ix_agent_exec_user_agent_started', table_name='agent_executions')
    op.add_column('agent_memories', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_agent_memories_agent_id'), 'agent_memories', ['agent_id'], unique=False)
    op.drop_column('agent_memories', 'metadata')
    op.alter_column('agent_templates', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_templates', 'required_tools',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_templates', 'use_case_examples',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_tools', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_versions', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index('ix_agents_configuration_gin', table_name='agents', postgresql_using='gin')
    op.drop_index('ix_agents_llm_provider', table_name='agents')
    op.alter_column('answer_feedback', 'suggestions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('answer_feedback', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('batch_uploads', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('block_test_cases', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('block_test_cases', 'expected_output',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('block_test_cases', 'assertions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('block_versions', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('blocks', 'input_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('blocks', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('blocks', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('branch_commits', 'snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_branch_commits_branch_id'), 'branch_commits', ['branch_id'], unique=False)
    op.alter_column('collaboration_sessions', 'cursor_position',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('collaboration_sessions', 'selection',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('cost_records', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_cost_records_agent_id'), 'cost_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cost_records_execution_id'), 'cost_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_cost_records_timestamp'), 'cost_records', ['timestamp'], unique=False)
    op.drop_column('cost_records', 'metadata')
    op.alter_column('documents', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_schedules', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_steps', 'step_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledgebase_versions', 'document_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('message_sources', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('messages', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('prompt_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('resource_shares', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tools', 'input_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tools', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_workflow_branches_workflow_id'), 'workflow_branches', ['workflow_id'], unique=False)
    op.alter_column('workflow_executions', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'output_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'execution_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_workflow_exec_status_started', table_name='workflow_executions')
    op.drop_index('ix_workflow_exec_user_started', table_name='workflow_executions')
    op.drop_index('ix_workflow_exec_user_workflow_status', table_name='workflow_executions')
    op.alter_column('workflow_nodes', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_schedules', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_subflows', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index('ix_workflows_graph_definition_gin', table_name='workflows', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workflows_graph_definition_gin', 'workflows', ['graph_definition'], unique=False, postgresql_using='gin')
    op.alter_column('workflow_subflows', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('workflow_schedules', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_workflow_exec_user_workflow_status', 'workflow_executions', ['user_id', 'workflow_id', 'status'], unique=False)
    op.create_index('ix_workflow_exec_user_started', 'workflow_executions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_workflow_exec_status_started', 'workflow_executions', ['status', 'started_at'], unique=False)
    op.alter_column('workflow_executions', 'execution_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_workflow_branches_workflow_id'), table_name='workflow_branches')
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tools', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tools', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('resource_shares', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('messages', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('message_sources', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledgebase_versions', 'document_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('execution_steps', 'step_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_schedules', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('cost_records', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cost_records_timestamp'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_execution_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_agent_id'), table_name='cost_records')
    op.drop_column('cost_records', 'meta_data')
    op.alter_column('collaboration_sessions', 'selection',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('collaboration_sessions', 'cursor_position',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_branch_commits_branch_id'), table_name='branch_commits')
    op.alter_column('branch_commits', 'snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('blocks', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('blocks', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('blocks', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('block_versions', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('block_test_cases', 'assertions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('block_test_cases', 'expected_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('block_test_cases', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('batch_uploads', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('answer_feedback', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('answer_feedback', 'suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_agents_llm_provider', 'agents', [sa.text("(configuration ->> 'llm_provider'::text)")], unique=False)
    op.create_index('ix_agents_configuration_gin', 'agents', ['configuration'], unique=False, postgresql_using='gin')
    op.alter_column('agent_versions', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_tools', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_templates', 'use_case_examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_templates', 'required_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_templates', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('agent_memories', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_memories_agent_id'), table_name='agent_memories')
    op.drop_column('agent_memories', 'meta_data')
    op.create_index('ix_agent_exec_user_agent_started', 'agent_executions', ['user_id', 'agent_id', 'started_at'], unique=False)
    op.create_index('ix_agent_exec_session_status', 'agent_executions', ['session_id', 'status'], unique=False)
    op.alter_column('agent_executions', 'execution_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_executions', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_executions', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_agent_blocks_config_gin', 'agent_blocks', ['config'], unique=False, postgresql_using='gin')
    op.alter_column('agent_blocks', 'outputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_blocks', 'inputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_blocks', 'sub_blocks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('custom_tool_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['custom_tools.id'], name='custom_tool_ratings_tool_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='custom_tool_ratings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='custom_tool_ratings_pkey')
    )
    op.create_index('idx_custom_tool_ratings_user_id', 'custom_tool_ratings', ['user_id'], unique=False)
    op.create_index('idx_custom_tool_ratings_tool_id', 'custom_tool_ratings', ['tool_id'], unique=False)
    op.create_table('custom_tools',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'custom'::character varying"), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), server_default=sa.text("'🔧'::character varying"), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), server_default=sa.text("'GET'::character varying"), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('query_params', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('body_template', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('requires_auth', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('auth_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('auth_config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_marketplace', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('test_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('last_test_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_test_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='custom_tools_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='custom_tools_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_custom_tools_user_id', 'custom_tools', ['user_id'], unique=False)
    op.create_index('idx_custom_tools_public', 'custom_tools', ['is_public'], unique=False)
    op.create_index('idx_custom_tools_marketplace', 'custom_tools', ['is_marketplace'], unique=False)
    op.create_index('idx_custom_tools_category', 'custom_tools', ['category'], unique=False)
    op.create_table('custom_tool_usage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='custom_tool_usage_agent_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['custom_tools.id'], name='custom_tool_usage_tool_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='custom_tool_usage_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='custom_tool_usage_pkey')
    )
    op.create_index('idx_custom_tool_usage_user_id', 'custom_tool_usage', ['user_id'], unique=False)
    op.create_index('idx_custom_tool_usage_tool_id', 'custom_tool_usage', ['tool_id'], unique=False)
    op.create_index('idx_custom_tool_usage_executed_at', 'custom_tool_usage', ['executed_at'], unique=False)
    op.drop_index('ix_trigger_executions_workflow_time', table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_workflow_id'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_triggered_at'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_trigger_type'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_trigger_id'), table_name='trigger_executions')
    op.drop_index('ix_trigger_executions_trigger', table_name='trigger_executions')
    op.drop_index('ix_trigger_executions_status_time', table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_status'), table_name='trigger_executions')
    op.drop_table('trigger_executions')
    op.drop_index('ix_user_api_keys_user_service', table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_index('ix_user_api_keys_active', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
