"""add_composite_indexes_and_constraints

Revision ID: 3cf740d85320
Revises: 9ce227b568e8
Create Date: 2025-10-07 20:30:31.735126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cf740d85320"
down_revision: Union[str, None] = "9ce227b568e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_documents_user_status", "documents", ["user_id", "status"], unique=False
    )
    op.create_index(
        "ix_documents_user_uploaded",
        "documents",
        ["user_id", "uploaded_at"],
        unique=False,
    )
    op.create_index(
        "ix_messages_session_created",
        "messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_messages_user_created", "messages", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_messages_user_session", "messages", ["user_id", "session_id"], unique=False
    )
    op.create_index(
        "ix_sessions_user_updated", "sessions", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_usage_logs_user_action_created",
        "usage_logs",
        ["user_id", "action", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_logs_user_action_created", table_name="usage_logs")
    op.drop_index("ix_sessions_user_updated", table_name="sessions")
    op.drop_index("ix_messages_user_session", table_name="messages")
    op.drop_index("ix_messages_user_created", table_name="messages")
    op.drop_index("ix_messages_session_created", table_name="messages")
    op.drop_index("ix_documents_user_uploaded", table_name="documents")
    op.drop_index("ix_documents_user_status", table_name="documents")
    # ### end Alembic commands ###
