"""Add tool execution tables

Revision ID: a0511f45fcf7
Revises: 19f074b5cae1
Create Date: 2025-12-27 20:54:06.514775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0511f45fcf7'
down_revision: Union[str, None] = '19f074b5cae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_case_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("flow_type IN ('agentflow', 'chatflow')", name='check_flow_template_type_valid'),
    sa.CheckConstraint('rating >= 0.0 AND rating <= 5.0', name='check_flow_template_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_templates_author_id'), 'flow_templates', ['author_id'], unique=False)
    op.create_index(op.f('ix_flow_templates_category'), 'flow_templates', ['category'], unique=False)
    op.create_index(op.f('ix_flow_templates_created_at'), 'flow_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_flow_templates_is_published'), 'flow_templates', ['is_published'], unique=False)
    op.create_index(op.f('ix_flow_templates_is_system'), 'flow_templates', ['is_system'], unique=False)
    op.create_index('ix_flow_templates_system_published', 'flow_templates', ['is_system', 'is_published'], unique=False)
    op.create_index('ix_flow_templates_type_category', 'flow_templates', ['flow_type', 'category'], unique=False)
    op.create_table('marketplace_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview_image', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("item_type IN ('agentflow', 'chatflow', 'workflow', 'tool', 'template')", name='check_marketplace_item_type_valid'),
    sa.CheckConstraint('rating >= 0.0 AND rating <= 5.0', name='check_marketplace_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_author_id'), 'marketplace_items', ['author_id'], unique=False)
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_items_created_at'), 'marketplace_items', ['created_at'], unique=False)
    op.create_index('ix_marketplace_items_featured', 'marketplace_items', ['is_featured', 'is_published'], unique=False)
    op.create_index(op.f('ix_marketplace_items_is_featured'), 'marketplace_items', ['is_featured'], unique=False)
    op.create_index(op.f('ix_marketplace_items_is_published'), 'marketplace_items', ['is_published'], unique=False)
    op.create_index('ix_marketplace_items_type_category', 'marketplace_items', ['item_type', 'category'], unique=False)
    op.create_table('tool_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_id', 'name', name='uq_user_tool_credential_name')
    )
    op.create_index(op.f('ix_tool_credentials_is_active'), 'tool_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_tool_credentials_tool_id'), 'tool_credentials', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_credentials_user_id'), 'tool_credentials', ['user_id'], unique=False)
    op.create_index('ix_tool_credentials_user_tool', 'tool_credentials', ['user_id', 'tool_id'], unique=False)
    op.create_table('tool_usage_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('avg_execution_time', sa.Float(), nullable=True),
    sa.Column('total_execution_time', sa.Float(), nullable=True),
    sa.Column('min_execution_time', sa.Float(), nullable=True),
    sa.Column('max_execution_time', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'user_id', 'date', name='uq_tool_user_date_metric')
    )
    op.create_index(op.f('ix_tool_usage_metrics_date'), 'tool_usage_metrics', ['date'], unique=False)
    op.create_index('ix_tool_usage_metrics_date_desc', 'tool_usage_metrics', [sa.text('date DESC')], unique=False)
    op.create_index('ix_tool_usage_metrics_tool_date', 'tool_usage_metrics', ['tool_id', 'date'], unique=False)
    op.create_index(op.f('ix_tool_usage_metrics_tool_id'), 'tool_usage_metrics', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_usage_metrics_user_id'), 'tool_usage_metrics', ['user_id'], unique=False)
    op.create_table('block_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('execution_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed', 'timeout')", name='check_block_execution_status_valid'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_executions_block_id'), 'block_executions', ['block_id'], unique=False)
    op.create_index('ix_block_executions_block_status', 'block_executions', ['block_id', 'status'], unique=False)
    op.create_index(op.f('ix_block_executions_created_at'), 'block_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_block_executions_status'), 'block_executions', ['status'], unique=False)
    op.create_index('ix_block_executions_user_created', 'block_executions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_block_executions_user_id'), 'block_executions', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('memory_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatflow_id'], ['chatflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_chatflow_id'), 'chat_sessions', ['chatflow_id'], unique=False)
    op.create_index('ix_chat_sessions_chatflow_updated', 'chat_sessions', ['chatflow_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_token'), 'chat_sessions', ['session_token'], unique=True)
    op.create_table('conversation_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'EDITOR', 'ADMIN', name='sharerole'), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_shares_session_id', 'conversation_shares', ['session_id'], unique=False)
    op.create_index('idx_conversation_shares_session_user', 'conversation_shares', ['session_id', 'user_id'], unique=True)
    op.create_index('idx_conversation_shares_user_id', 'conversation_shares', ['user_id'], unique=False)
    op.create_table('embed_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embed_token', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('widget_title', sa.String(length=255), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('placeholder_text', sa.String(length=255), nullable=True),
    sa.Column('show_branding', sa.Boolean(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit_per_ip', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatflow_id'], ['chatflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embed_configs_chatflow_active', 'embed_configs', ['chatflow_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_embed_configs_chatflow_id'), 'embed_configs', ['chatflow_id'], unique=False)
    op.create_index(op.f('ix_embed_configs_embed_token'), 'embed_configs', ['embed_token'], unique=True)
    op.create_index(op.f('ix_embed_configs_is_active'), 'embed_configs', ['is_active'], unique=False)
    op.create_index('ix_embed_configs_token', 'embed_configs', ['embed_token'], unique=False)
    op.create_index(op.f('ix_embed_configs_user_id'), 'embed_configs', ['user_id'], unique=False)
    op.create_table('marketplace_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_review_rating_range'),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_marketplace_review_user')
    )
    op.create_index(op.f('ix_marketplace_reviews_created_at'), 'marketplace_reviews', ['created_at'], unique=False)
    op.create_index('ix_marketplace_reviews_item_created', 'marketplace_reviews', ['item_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_item_id'), 'marketplace_reviews', ['item_id'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_user_id'), 'marketplace_reviews', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='check_message_role_valid'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_execution_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('debug', 'info', 'warn', 'error')", name='check_log_level_valid'),
    sa.ForeignKeyConstraint(['flow_execution_id'], ['flow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_flow_execution_id'), 'execution_logs', ['flow_execution_id'], unique=False)
    op.create_index('ix_execution_logs_flow_timestamp', 'execution_logs', ['flow_execution_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_execution_logs_timestamp'), 'execution_logs', ['timestamp'], unique=False)
    op.create_table('node_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('node_label', sa.String(length=255), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name='check_node_execution_status_valid'),
    sa.ForeignKeyConstraint(['flow_execution_id'], ['flow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_executions_flow_execution_id'), 'node_executions', ['flow_execution_id'], unique=False)
    op.create_index('ix_node_executions_flow_status', 'node_executions', ['flow_execution_id', 'status'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credentials_used', sa.Boolean(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_agent_id'), 'tool_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_session_id'), 'tool_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_started_at'), 'tool_executions', ['started_at'], unique=False)
    op.create_index('ix_tool_executions_started_at_desc', 'tool_executions', [sa.text('started_at DESC')], unique=False)
    op.create_index(op.f('ix_tool_executions_success'), 'tool_executions', ['success'], unique=False)
    op.create_index('ix_tool_executions_success_started', 'tool_executions', ['success', 'started_at'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_id'), 'tool_executions', ['tool_id'], unique=False)
    op.create_index('ix_tool_executions_tool_user', 'tool_executions', ['tool_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_user_id'), 'tool_executions', ['user_id'], unique=False)
    op.drop_index('idx_aggregate_type_timestamp', table_name='event_store')
    op.drop_index('idx_aggregate_version', table_name='event_store')
    op.drop_index('idx_user_timestamp', table_name='event_store')
    op.drop_index('ix_event_store_aggregate_id', table_name='event_store')
    op.drop_index('ix_event_store_aggregate_type', table_name='event_store')
    op.drop_index('ix_event_store_event_type', table_name='event_store')
    op.drop_index('ix_event_store_id', table_name='event_store')
    op.drop_index('ix_event_store_timestamp', table_name='event_store')
    op.drop_index('ix_event_store_user_id', table_name='event_store')
    op.drop_table('event_store')
    op.drop_index('ix_kg_queries_kg_user', table_name='kg_queries')
    op.drop_index('ix_kg_queries_type_created', table_name='kg_queries')
    op.drop_table('kg_queries')
    op.drop_index('ix_kg_relationships_confidence', table_name='kg_relationships')
    op.drop_index('ix_kg_relationships_kg_type', table_name='kg_relationships')
    op.drop_index('ix_kg_relationships_source_target', table_name='kg_relationships')
    op.drop_index('ix_kg_relationships_temporal', table_name='kg_relationships')
    op.drop_table('kg_relationships')
    op.drop_index('ix_kg_mentions_confidence', table_name='kg_entity_mentions')
    op.drop_index('ix_kg_mentions_entity_doc', table_name='kg_entity_mentions')
    op.drop_table('kg_entity_mentions')
    op.drop_table('kg_schemas')
    op.drop_index('ix_kg_entities_canonical', table_name='kg_entities')
    op.drop_index('ix_kg_entities_confidence', table_name='kg_entities')
    op.drop_index('ix_kg_entities_kg_type', table_name='kg_entities')
    op.drop_table('kg_entities')
    op.drop_index('ix_kg_jobs_kg_status', table_name='kg_extraction_jobs')
    op.drop_index('ix_kg_jobs_user_created', table_name='kg_extraction_jobs')
    op.drop_table('kg_extraction_jobs')
    op.drop_index('ix_kg_user_created', table_name='knowledge_graphs')
    op.drop_table('knowledge_graphs')
    op.create_index(op.f('ix_agentflow_agents_block_id'), 'agentflow_agents', ['block_id'], unique=False)
    op.alter_column('agentflow_edges', 'edge_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_agentflow_edges_agentflow_id'), 'agentflow_edges', ['agentflow_id'], unique=False)
    op.alter_column('agentflows', 'orchestration_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Orchestration type: sequential, parallel, hierarchical, adaptive, \n             2025 trends: consensus_building, dynamic_routing, swarm_intelligence, event_driven, reflection,\n             2026 trends: neuromorphic, quantum_enhanced, bio_inspired, self_evolving, federated, emotional_ai, predictive',
               existing_nullable=False)
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.drop_index('idx_api_keys_expires_at', table_name='api_keys')
    op.drop_index('idx_api_keys_is_active', table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.alter_column('chatflow_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledgebases', 'milvus_collection_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('knowledgebases', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_knowledgebases_kb_type'), 'knowledgebases', ['kb_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledgebases_kb_type'), table_name='knowledgebases')
    op.alter_column('knowledgebases', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('knowledgebases', 'milvus_collection_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('chatflow_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_keys_expires_at', 'api_keys', ['expires_at'], unique=False)
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    op.alter_column('agentflows', 'orchestration_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Orchestration type: sequential, parallel, hierarchical, adaptive, \n             2025 trends: consensus_building, dynamic_routing, swarm_intelligence, event_driven, reflection,\n             2026 trends: neuromorphic, quantum_enhanced, bio_inspired, self_evolving, federated, emotional_ai, predictive',
               existing_nullable=False)
    op.drop_index(op.f('ix_agentflow_edges_agentflow_id'), table_name='agentflow_edges')
    op.alter_column('agentflow_edges', 'edge_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_agentflow_agents_block_id'), table_name='agentflow_agents')
    op.create_table('knowledge_graphs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledgebase_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_extraction_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('entity_extraction_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('relation_extraction_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationship_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("processing_status::text = ANY (ARRAY['ready'::character varying, 'processing'::character varying, 'error'::character varying, 'updating'::character varying]::text[])", name='check_kg_processing_status_valid'),
    sa.ForeignKeyConstraint(['knowledgebase_id'], ['knowledgebases.id'], name='knowledge_graphs_knowledgebase_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='knowledge_graphs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='knowledge_graphs_pkey'),
    sa.UniqueConstraint('knowledgebase_id', name='knowledge_graphs_knowledgebase_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_kg_user_created', 'knowledge_graphs', ['user_id', 'created_at'], unique=False)
    op.create_table('kg_extraction_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_graph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('documents_to_process', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('documents_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('documents_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entities_extracted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationships_extracted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estimated_completion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("job_type::text = ANY (ARRAY['full_extraction'::character varying, 'incremental'::character varying, 'document_specific'::character varying, 'schema_update'::character varying]::text[])", name='check_kg_job_type_valid'),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])", name='check_kg_job_status_valid'),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name='kg_extraction_jobs_knowledge_graph_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='kg_extraction_jobs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kg_extraction_jobs_pkey')
    )
    op.create_index('ix_kg_jobs_user_created', 'kg_extraction_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_kg_jobs_kg_status', 'kg_extraction_jobs', ['knowledge_graph_id', 'status'], unique=False)
    op.create_table('kg_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_graph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canonical_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extraction_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_documents', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_chunks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mention_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationship_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0::double precision AND confidence_score <= 1.0::double precision', name='check_entity_confidence_range'),
    sa.CheckConstraint('mention_count >= 0', name='check_entity_mention_count_positive'),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name='kg_entities_knowledge_graph_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kg_entities_pkey'),
    sa.UniqueConstraint('knowledge_graph_id', 'canonical_name', name='uq_kg_entity_canonical'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_kg_entities_kg_type', 'kg_entities', ['knowledge_graph_id', 'entity_type'], unique=False)
    op.create_index('ix_kg_entities_confidence', 'kg_entities', ['confidence_score'], unique=False)
    op.create_index('ix_kg_entities_canonical', 'kg_entities', ['canonical_name'], unique=False)
    op.create_table('kg_schemas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_graph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('relationship_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name='kg_schemas_knowledge_graph_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kg_schemas_pkey'),
    sa.UniqueConstraint('knowledge_graph_id', 'name', name='uq_kg_schema_name')
    )
    op.create_table('kg_entity_mentions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('mention_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context_before', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_after', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0::double precision AND confidence_score <= 1.0::double precision', name='check_mention_confidence_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='kg_entity_mentions_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['kg_entities.id'], name='kg_entity_mentions_entity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kg_entity_mentions_pkey')
    )
    op.create_index('ix_kg_mentions_entity_doc', 'kg_entity_mentions', ['entity_id', 'document_id'], unique=False)
    op.create_index('ix_kg_mentions_confidence', 'kg_entity_mentions', ['confidence_score'], unique=False)
    op.create_table('kg_relationships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_graph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('relation_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_bidirectional', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extraction_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_documents', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_chunks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_sentences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('temporal_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('temporal_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mention_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0::double precision AND confidence_score <= 1.0::double precision', name='check_relationship_confidence_range'),
    sa.CheckConstraint('mention_count >= 0', name='check_relationship_mention_count_positive'),
    sa.CheckConstraint('source_entity_id <> target_entity_id', name='check_no_self_relationship'),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name='kg_relationships_knowledge_graph_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['kg_entities.id'], name='kg_relationships_source_entity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['kg_entities.id'], name='kg_relationships_target_entity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kg_relationships_pkey'),
    sa.UniqueConstraint('knowledge_graph_id', 'source_entity_id', 'target_entity_id', 'relation_type', name='uq_kg_relationship')
    )
    op.create_index('ix_kg_relationships_temporal', 'kg_relationships', ['temporal_start', 'temporal_end'], unique=False)
    op.create_index('ix_kg_relationships_source_target', 'kg_relationships', ['source_entity_id', 'target_entity_id'], unique=False)
    op.create_index('ix_kg_relationships_kg_type', 'kg_relationships', ['knowledge_graph_id', 'relation_type'], unique=False)
    op.create_index('ix_kg_relationships_confidence', 'kg_relationships', ['confidence_score'], unique=False)
    op.create_table('kg_queries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_graph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('query_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query_parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("query_type::text = ANY (ARRAY['entity_search'::character varying, 'relationship_search'::character varying, 'path_finding'::character varying, 'subgraph'::character varying, 'similarity'::character varying, 'custom'::character varying]::text[])", name='check_kg_query_type_valid'),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name='kg_queries_knowledge_graph_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='kg_queries_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kg_queries_pkey')
    )
    op.create_index('ix_kg_queries_type_created', 'kg_queries', ['query_type', 'created_at'], unique=False)
    op.create_index('ix_kg_queries_kg_user', 'kg_queries', ['knowledge_graph_id', 'user_id'], unique=False)
    op.create_table('event_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aggregate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('aggregate_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='event_store_pkey')
    )
    op.create_index('ix_event_store_user_id', 'event_store', ['user_id'], unique=False)
    op.create_index('ix_event_store_timestamp', 'event_store', ['timestamp'], unique=False)
    op.create_index('ix_event_store_id', 'event_store', ['id'], unique=False)
    op.create_index('ix_event_store_event_type', 'event_store', ['event_type'], unique=False)
    op.create_index('ix_event_store_aggregate_type', 'event_store', ['aggregate_type'], unique=False)
    op.create_index('ix_event_store_aggregate_id', 'event_store', ['aggregate_id'], unique=False)
    op.create_index('idx_user_timestamp', 'event_store', ['user_id', 'timestamp'], unique=False)
    op.create_index('idx_aggregate_version', 'event_store', ['aggregate_id', 'version'], unique=False)
    op.create_index('idx_aggregate_type_timestamp', 'event_store', ['aggregate_type', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_tool_executions_user_id'), table_name='tool_executions')
    op.drop_index('ix_tool_executions_tool_user', table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_tool_id'), table_name='tool_executions')
    op.drop_index('ix_tool_executions_success_started', table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_success'), table_name='tool_executions')
    op.drop_index('ix_tool_executions_started_at_desc', table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_started_at'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_session_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_agent_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index('ix_node_executions_flow_status', table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_flow_execution_id'), table_name='node_executions')
    op.drop_table('node_executions')
    op.drop_index(op.f('ix_execution_logs_timestamp'), table_name='execution_logs')
    op.drop_index('ix_execution_logs_flow_timestamp', table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_flow_execution_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_marketplace_reviews_user_id'), table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_item_id'), table_name='marketplace_reviews')
    op.drop_index('ix_marketplace_reviews_item_created', table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_created_at'), table_name='marketplace_reviews')
    op.drop_table('marketplace_reviews')
    op.drop_index(op.f('ix_embed_configs_user_id'), table_name='embed_configs')
    op.drop_index('ix_embed_configs_token', table_name='embed_configs')
    op.drop_index(op.f('ix_embed_configs_is_active'), table_name='embed_configs')
    op.drop_index(op.f('ix_embed_configs_embed_token'), table_name='embed_configs')
    op.drop_index(op.f('ix_embed_configs_chatflow_id'), table_name='embed_configs')
    op.drop_index('ix_embed_configs_chatflow_active', table_name='embed_configs')
    op.drop_table('embed_configs')
    op.drop_index('idx_conversation_shares_user_id', table_name='conversation_shares')
    op.drop_index('idx_conversation_shares_session_user', table_name='conversation_shares')
    op.drop_index('idx_conversation_shares_session_id', table_name='conversation_shares')
    op.drop_table('conversation_shares')
    op.drop_index(op.f('ix_chat_sessions_session_token'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_chatflow_updated', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_chatflow_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_block_executions_user_id'), table_name='block_executions')
    op.drop_index('ix_block_executions_user_created', table_name='block_executions')
    op.drop_index(op.f('ix_block_executions_status'), table_name='block_executions')
    op.drop_index(op.f('ix_block_executions_created_at'), table_name='block_executions')
    op.drop_index('ix_block_executions_block_status', table_name='block_executions')
    op.drop_index(op.f('ix_block_executions_block_id'), table_name='block_executions')
    op.drop_table('block_executions')
    op.drop_index(op.f('ix_tool_usage_metrics_user_id'), table_name='tool_usage_metrics')
    op.drop_index(op.f('ix_tool_usage_metrics_tool_id'), table_name='tool_usage_metrics')
    op.drop_index('ix_tool_usage_metrics_tool_date', table_name='tool_usage_metrics')
    op.drop_index('ix_tool_usage_metrics_date_desc', table_name='tool_usage_metrics')
    op.drop_index(op.f('ix_tool_usage_metrics_date'), table_name='tool_usage_metrics')
    op.drop_table('tool_usage_metrics')
    op.drop_index('ix_tool_credentials_user_tool', table_name='tool_credentials')
    op.drop_index(op.f('ix_tool_credentials_user_id'), table_name='tool_credentials')
    op.drop_index(op.f('ix_tool_credentials_tool_id'), table_name='tool_credentials')
    op.drop_index(op.f('ix_tool_credentials_is_active'), table_name='tool_credentials')
    op.drop_table('tool_credentials')
    op.drop_index('ix_marketplace_items_type_category', table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_is_published'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_is_featured'), table_name='marketplace_items')
    op.drop_index('ix_marketplace_items_featured', table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_created_at'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_author_id'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index('ix_flow_templates_type_category', table_name='flow_templates')
    op.drop_index('ix_flow_templates_system_published', table_name='flow_templates')
    op.drop_index(op.f('ix_flow_templates_is_system'), table_name='flow_templates')
    op.drop_index(op.f('ix_flow_templates_is_published'), table_name='flow_templates')
    op.drop_index(op.f('ix_flow_templates_created_at'), table_name='flow_templates')
    op.drop_index(op.f('ix_flow_templates_category'), table_name='flow_templates')
    op.drop_index(op.f('ix_flow_templates_author_id'), table_name='flow_templates')
    op.drop_table('flow_templates')
    # ### end Alembic commands ###
