"""Add Agent Builder tables and models

Revision ID: b667d05f8afb
Revises: 641d3018cdb5
Create Date: 2025-11-04 22:34:23.058677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b667d05f8afb'
down_revision: Union[str, None] = '641d3018cdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('required_tools', sa.JSON(), nullable=True),
    sa.Column('use_case_examples', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 0.0 AND rating <= 5.0', name='check_rating_range'),
    sa.CheckConstraint('usage_count >= 0', name='check_usage_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_templates_category'), 'agent_templates', ['category'], unique=False)
    op.create_index(op.f('ix_agent_templates_is_published'), 'agent_templates', ['is_published'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_credentials_tool_id'), 'oauth_credentials', ['tool_id'], unique=False)
    op.create_index(op.f('ix_oauth_credentials_user_id'), 'oauth_credentials', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('implementation_type', sa.String(length=50), nullable=False),
    sa.Column('implementation_ref', sa.String(length=500), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("implementation_type IN ('langchain', 'custom', 'builtin')", name='check_tool_implementation_type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_category'), 'tools', ['category'], unique=False)
    op.create_index(op.f('ix_tools_is_builtin'), 'tools', ['is_builtin'], unique=False)
    op.create_table('variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("scope IN ('global', 'workspace', 'user', 'agent')", name='check_variable_scope_valid'),
    sa.CheckConstraint("value_type IN ('string', 'number', 'boolean', 'json')", name='check_variable_type_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', 'scope_id', name='uq_variable_scope')
    )
    op.create_index(op.f('ix_variables_deleted_at'), 'variables', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_variables_is_secret'), 'variables', ['is_secret'], unique=False)
    op.create_index(op.f('ix_variables_name'), 'variables', ['name'], unique=False)
    op.create_index(op.f('ix_variables_scope'), 'variables', ['scope'], unique=False)
    op.create_index(op.f('ix_variables_scope_id'), 'variables', ['scope_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("block_type IN ('llm', 'tool', 'logic', 'composite')", name='check_block_type_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_block_name_per_user')
    )
    op.create_index(op.f('ix_blocks_block_type'), 'blocks', ['block_type'], unique=False)
    op.create_index(op.f('ix_blocks_is_public'), 'blocks', ['is_public'], unique=False)
    op.create_index(op.f('ix_blocks_user_id'), 'blocks', ['user_id'], unique=False)
    op.create_index('ix_blocks_user_public', 'blocks', ['user_id', 'is_public'], unique=False)
    op.create_index('ix_blocks_user_type', 'blocks', ['user_id', 'block_type'], unique=False)
    op.create_table('knowledgebases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('milvus_collection_name', sa.String(length=255), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('chunk_overlap >= 0', name='check_chunk_overlap_positive'),
    sa.CheckConstraint('chunk_size > 0', name='check_chunk_size_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebases_created_at'), 'knowledgebases', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledgebases_milvus_collection_name'), 'knowledgebases', ['milvus_collection_name'], unique=True)
    op.create_index(op.f('ix_knowledgebases_user_id'), 'knowledgebases', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('read', 'write', 'execute', 'delete', 'share', 'admin')", name='check_permission_action_valid'),
    sa.CheckConstraint("resource_type IN ('agent', 'block', 'workflow', 'knowledgebase')", name='check_permission_resource_type_valid'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_type', 'resource_id', 'action', name='uq_permission')
    )
    op.create_index('ix_permissions_resource', 'permissions', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_permissions_resource_id'), 'permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_permissions_resource_type'), 'permissions', ['resource_type'], unique=False)
    op.create_index(op.f('ix_permissions_user_id'), 'permissions', ['user_id'], unique=False)
    op.create_index('ix_permissions_user_resource', 'permissions', ['user_id', 'resource_type', 'resource_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_templates_is_system'), 'prompt_templates', ['is_system'], unique=False)
    op.create_table('resource_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("resource_type IN ('agent', 'block', 'workflow', 'knowledgebase')", name='check_share_resource_type_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_shares_created_by'), 'resource_shares', ['created_by'], unique=False)
    op.create_index(op.f('ix_resource_shares_expires_at'), 'resource_shares', ['expires_at'], unique=False)
    op.create_index('ix_resource_shares_resource', 'resource_shares', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_resource_id'), 'resource_shares', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_resource_type'), 'resource_shares', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resource_shares_share_token'), 'resource_shares', ['share_token'], unique=True)
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_variable_id'), 'secrets', ['variable_id'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph_definition', sa.JSON(), nullable=False),
    sa.Column('compiled_graph', sa.LargeBinary(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_is_public'), 'workflows', ['is_public'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_index('ix_workflows_user_public', 'workflows', ['user_id', 'is_public'], unique=False)
    op.create_table('agent_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('sub_blocks', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_blocks_type'), 'agent_blocks', ['type'], unique=False)
    op.create_index('ix_agent_blocks_workflow_enabled', 'agent_blocks', ['workflow_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_agent_blocks_workflow_id'), 'agent_blocks', ['workflow_id'], unique=False)
    op.create_index('ix_agent_blocks_workflow_type', 'agent_blocks', ['workflow_id', 'type'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("agent_type IN ('custom', 'template_based')", name='check_agent_type_valid'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_deleted_at'), 'agents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agents_is_public'), 'agents', ['is_public'], unique=False)
    op.create_index('ix_agents_user_created', 'agents', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_index('ix_agents_user_type', 'agents', ['user_id', 'agent_type'], unique=False)
    op.create_table('block_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_block_id', sa.UUID(), nullable=False),
    sa.Column('child_block_id', sa.UUID(), nullable=False),
    sa.Column('version_constraint', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['child_block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_block_id', 'child_block_id', name='uq_block_dependency')
    )
    op.create_index(op.f('ix_block_dependencies_child_block_id'), 'block_dependencies', ['child_block_id'], unique=False)
    op.create_index(op.f('ix_block_dependencies_parent_block_id'), 'block_dependencies', ['parent_block_id'], unique=False)
    op.create_table('block_test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=False),
    sa.Column('assertions', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("last_run_status IS NULL OR last_run_status IN ('passed', 'failed', 'error')", name='check_test_status_valid'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_test_cases_block_id'), 'block_test_cases', ['block_id'], unique=False)
    op.create_table('block_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('is_breaking_change', sa.Boolean(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_block_versions_block_created', 'block_versions', ['block_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_block_versions_block_id'), 'block_versions', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_versions_created_at'), 'block_versions', ['created_at'], unique=False)
    op.create_table('knowledgebase_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledgebase_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledgebase_id'], ['knowledgebases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledgebase_id', 'document_id', name='uq_kb_document')
    )
    op.create_index(op.f('ix_knowledgebase_documents_document_id'), 'knowledgebase_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledgebase_documents_knowledgebase_id'), 'knowledgebase_documents', ['knowledgebase_id'], unique=False)
    op.create_table('knowledgebase_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledgebase_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('document_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('version_number > 0', name='check_kb_version_positive'),
    sa.ForeignKeyConstraint(['knowledgebase_id'], ['knowledgebases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_versions_kb_created', 'knowledgebase_versions', ['knowledgebase_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_knowledgebase_versions_created_at'), 'knowledgebase_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledgebase_versions_knowledgebase_id'), 'knowledgebase_versions', ['knowledgebase_id'], unique=False)
    op.create_table('prompt_template_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_template_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_template_versions_prompt_template_id'), 'prompt_template_versions', ['prompt_template_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'timeout', 'cancelled')", name='check_workflow_execution_status_valid'),
    sa.CheckConstraint('duration_ms >= 0', name='check_workflow_duration_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_session_id'), 'workflow_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_started_at'), 'workflow_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_user_id'), 'workflow_executions', ['user_id'], unique=False)
    op.create_index('ix_workflow_executions_user_status', 'workflow_executions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_executions_workflow_started', 'workflow_executions', ['workflow_id', 'started_at'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('node_ref_id', sa.UUID(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.CheckConstraint("node_type IN ('agent', 'block', 'control')", name='check_node_type_valid'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_nodes_workflow_id'), 'workflow_nodes', ['workflow_id'], unique=False)
    op.create_table('workflow_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('next_execution_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_schedules_is_active'), 'workflow_schedules', ['is_active'], unique=False)
    op.create_index('ix_workflow_schedules_next_execution', 'workflow_schedules', ['is_active', 'next_execution_at'], unique=False)
    op.create_index(op.f('ix_workflow_schedules_next_execution_at'), 'workflow_schedules', ['next_execution_at'], unique=False)
    op.create_index('ix_workflow_schedules_workflow_active', 'workflow_schedules', ['workflow_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflow_schedules_workflow_id'), 'workflow_schedules', ['workflow_id'], unique=False)
    op.create_table('workflow_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('webhook_path', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("http_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')", name='check_webhook_method_valid'),
    sa.CheckConstraint('trigger_count >= 0', name='check_trigger_count_positive'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_webhooks_is_active'), 'workflow_webhooks', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflow_webhooks_webhook_path'), 'workflow_webhooks', ['webhook_path'], unique=True)
    op.create_index('ix_workflow_webhooks_workflow_active', 'workflow_webhooks', ['workflow_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflow_webhooks_workflow_id'), 'workflow_webhooks', ['workflow_id'], unique=False)
    op.create_table('agent_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('source_block_id', sa.UUID(), nullable=False),
    sa.Column('target_block_id', sa.UUID(), nullable=False),
    sa.Column('source_handle', sa.String(length=50), nullable=True),
    sa.Column('target_handle', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_block_id'], ['agent_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_block_id'], ['agent_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_edges_source', 'agent_edges', ['source_block_id'], unique=False)
    op.create_index(op.f('ix_agent_edges_source_block_id'), 'agent_edges', ['source_block_id'], unique=False)
    op.create_index('ix_agent_edges_target', 'agent_edges', ['target_block_id'], unique=False)
    op.create_index(op.f('ix_agent_edges_target_block_id'), 'agent_edges', ['target_block_id'], unique=False)
    op.create_index('ix_agent_edges_workflow', 'agent_edges', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_agent_edges_workflow_id'), 'agent_edges', ['workflow_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'timeout', 'cancelled')", name='check_agent_execution_status_valid'),
    sa.CheckConstraint('duration_ms >= 0', name='check_agent_duration_positive'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_id'), 'agent_executions', ['agent_id'], unique=False)
    op.create_index('ix_agent_executions_agent_started', 'agent_executions', ['agent_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_session_id'), 'agent_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_started_at'), 'agent_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index('ix_agent_executions_status_started', 'agent_executions', ['status', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_user_id'), 'agent_executions', ['user_id'], unique=False)
    op.create_index('ix_agent_executions_user_status', 'agent_executions', ['user_id', 'status'], unique=False)
    op.create_table('agent_knowledgebases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('knowledgebase_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledgebase_id'], ['knowledgebases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'knowledgebase_id', name='uq_agent_kb')
    )
    op.create_index('ix_agent_kb_agent_priority', 'agent_knowledgebases', ['agent_id', 'priority'], unique=False)
    op.create_index(op.f('ix_agent_knowledgebases_agent_id'), 'agent_knowledgebases', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledgebases_knowledgebase_id'), 'agent_knowledgebases', ['knowledgebase_id'], unique=False)
    op.create_table('agent_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(length=100), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_id', name='uq_agent_tool')
    )
    op.create_index(op.f('ix_agent_tools_agent_id'), 'agent_tools', ['agent_id'], unique=False)
    op.create_index('ix_agent_tools_agent_order', 'agent_tools', ['agent_id', 'order'], unique=False)
    op.create_index(op.f('ix_agent_tools_tool_id'), 'agent_tools', ['tool_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_versions_agent_created', 'agent_versions', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_versions_created_at'), 'agent_versions', ['created_at'], unique=False)
    op.create_table('execution_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('next_execution_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_schedules_agent_active', 'execution_schedules', ['agent_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_execution_schedules_agent_id'), 'execution_schedules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_execution_schedules_is_active'), 'execution_schedules', ['is_active'], unique=False)
    op.create_index('ix_execution_schedules_next_execution', 'execution_schedules', ['is_active', 'next_execution_at'], unique=False)
    op.create_index(op.f('ix_execution_schedules_next_execution_at'), 'execution_schedules', ['next_execution_at'], unique=False)
    op.create_index(op.f('ix_execution_schedules_user_id'), 'execution_schedules', ['user_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.CheckConstraint("edge_type IN ('normal', 'conditional')", name='check_edge_type_valid'),
    sa.ForeignKeyConstraint(['source_node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_edges_source_node_id'), 'workflow_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_workflow_edges_target_node_id'), 'workflow_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_workflow_edges_workflow_id'), 'workflow_edges', ['workflow_id'], unique=False)
    op.create_table('workflow_subflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('parent_block_id', sa.UUID(), nullable=False),
    sa.Column('subflow_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("subflow_type IN ('loop', 'parallel')", name='check_subflow_type_valid'),
    sa.ForeignKeyConstraint(['parent_block_id'], ['agent_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_subflows_parent_block', 'workflow_subflows', ['parent_block_id'], unique=False)
    op.create_index(op.f('ix_workflow_subflows_parent_block_id'), 'workflow_subflows', ['parent_block_id'], unique=False)
    op.create_index(op.f('ix_workflow_subflows_subflow_type'), 'workflow_subflows', ['subflow_type'], unique=False)
    op.create_index(op.f('ix_workflow_subflows_workflow_id'), 'workflow_subflows', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_subflows_workflow_type', 'workflow_subflows', ['workflow_id', 'subflow_type'], unique=False)
    op.create_table('execution_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=True),
    sa.Column('llm_total_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=True),
    sa.Column('tool_total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit_count', sa.Integer(), nullable=True),
    sa.Column('cache_miss_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('cache_hit_count >= 0', name='check_cache_hit_positive'),
    sa.CheckConstraint('cache_miss_count >= 0', name='check_cache_miss_positive'),
    sa.CheckConstraint('llm_call_count >= 0', name='check_llm_call_count_positive'),
    sa.CheckConstraint('llm_total_tokens >= 0', name='check_llm_tokens_positive'),
    sa.CheckConstraint('tool_call_count >= 0', name='check_tool_call_count_positive'),
    sa.CheckConstraint('tool_total_duration_ms >= 0', name='check_tool_duration_positive'),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_metrics_execution_id'), 'execution_metrics', ['execution_id'], unique=True)
    op.create_table('execution_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('step_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('step_number >= 0', name='check_step_number_positive'),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_steps_execution_id'), 'execution_steps', ['execution_id'], unique=False)
    op.create_index('ix_execution_steps_execution_number', 'execution_steps', ['execution_id', 'step_number'], unique=False)
    op.create_index('ix_execution_steps_execution_timestamp', 'execution_steps', ['execution_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_execution_steps_timestamp'), 'execution_steps', ['timestamp'], unique=False)
    op.drop_index('idx_file_upload_created', table_name='file_upload_stats')
    op.drop_index('idx_file_upload_created_status', table_name='file_upload_stats')
    op.drop_index('idx_file_upload_file_id', table_name='file_upload_stats')
    op.drop_index('idx_file_upload_type', table_name='file_upload_stats')
    op.drop_table('file_upload_stats')
    op.drop_index('idx_rag_complexity', table_name='rag_processing_stats')
    op.drop_index('idx_rag_created', table_name='rag_processing_stats')
    op.drop_index('idx_rag_created_mode', table_name='rag_processing_stats')
    op.drop_index('idx_rag_session_id', table_name='rag_processing_stats')
    op.drop_index('idx_rag_success', table_name='rag_processing_stats')
    op.drop_table('rag_processing_stats')
    op.drop_index('idx_search_cache', table_name='hybrid_search_stats')
    op.drop_index('idx_search_created', table_name='hybrid_search_stats')
    op.drop_index('idx_search_created_type', table_name='hybrid_search_stats')
    op.drop_index('idx_search_session_id', table_name='hybrid_search_stats')
    op.drop_table('hybrid_search_stats')
    op.drop_index('idx_daily_trend_date', table_name='daily_accuracy_trends')
    op.drop_table('daily_accuracy_trends')
    op.drop_table('migration_history')
    op.drop_index('idx_embedding_created', table_name='embedding_stats')
    op.drop_index('idx_embedding_document_id', table_name='embedding_stats')
    op.drop_index('idx_embedding_model', table_name='embedding_stats')
    op.drop_table('embedding_stats')
    op.drop_index('ix_group_members_group', table_name='group_members')
    op.drop_index('ix_group_members_user', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_index('ix_feedback_message_id', table_name='feedback')
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_system_config_key', table_name='system_config')
    op.drop_table('system_config')
    op.drop_index('ix_query_logs_confidence_score', table_name='query_logs')
    op.drop_index('ix_query_logs_created_at', table_name='query_logs')
    op.drop_index('ix_query_logs_query_mode', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index('ix_document_permissions_document', table_name='document_permissions')
    op.drop_index('ix_document_permissions_expires', table_name='document_permissions')
    op.drop_index('ix_document_permissions_group', table_name='document_permissions')
    op.drop_index('ix_document_permissions_user', table_name='document_permissions')
    op.drop_table('document_permissions')
    op.drop_index('ix_groups_created_by', table_name='groups')
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_table('groups')
    op.alter_column('answer_feedback', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Overall quality score (0-1)',
               existing_nullable=False)
    op.alter_column('answer_feedback', 'grounding_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='How well answer is grounded in sources (0-1)',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'hallucination_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Risk of hallucination (0-1, higher = more risk)',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'user_rating',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User feedback: 1=good, 0=neutral, -1=bad',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'quality_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Quality level: excellent, good, acceptable, poor, very_poor',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('answer_feedback', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_feedback_overall_score', table_name='answer_feedback')
    op.drop_index('ix_feedback_quality_created', table_name='answer_feedback')
    op.drop_index('ix_feedback_rating_created', table_name='answer_feedback')
    op.drop_index('ix_feedback_session_id', table_name='answer_feedback')
    op.drop_index('ix_feedback_quality_level', table_name='answer_feedback')
    op.create_index('ix_feedback_quality_level', 'answer_feedback', ['quality_level', 'created_at'], unique=False)
    op.drop_index('ix_feedback_user_rating', table_name='answer_feedback')
    op.create_index('ix_feedback_user_rating', 'answer_feedback', ['user_rating', 'created_at'], unique=False)
    op.create_index(op.f('ix_answer_feedback_created_at'), 'answer_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_answer_feedback_message_id'), 'answer_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_answer_feedback_overall_score'), 'answer_feedback', ['overall_score'], unique=False)
    op.create_index(op.f('ix_answer_feedback_quality_level'), 'answer_feedback', ['quality_level'], unique=False)
    op.create_index(op.f('ix_answer_feedback_session_id'), 'answer_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_answer_feedback_user_id'), 'answer_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_feedback_user_rating'), 'answer_feedback', ['user_rating'], unique=False)
    op.drop_table_comment(
        'answer_feedback',
        existing_comment='Tracks answer quality metrics and user feedback',
        schema=None
    )
    op.alter_column('documents', 'document_title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Extracted document title',
               existing_nullable=True)
    op.alter_column('documents', 'document_author',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Extracted document author',
               existing_nullable=True)
    op.alter_column('documents', 'document_subject',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Extracted document subject/description',
               existing_nullable=True)
    op.alter_column('documents', 'document_keywords',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Extracted keywords (comma-separated)',
               existing_nullable=True)
    op.alter_column('documents', 'document_language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Detected language (ISO 639-1 code)',
               existing_nullable=True)
    op.alter_column('documents', 'document_creation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Document creation date (from metadata)',
               existing_nullable=True)
    op.alter_column('documents', 'document_modification_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Document last modification date (from metadata)',
               existing_nullable=True)
    op.drop_index('ix_documents_author', table_name='documents')
    op.drop_index('ix_documents_creation_date', table_name='documents')
    op.drop_index('ix_documents_language', table_name='documents')
    op.drop_index('ix_documents_title', table_name='documents', postgresql_using='gin')
    op.create_index('ix_documents_user_filename', 'documents', ['user_id', 'filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_user_filename', table_name='documents')
    op.create_index('ix_documents_title', 'documents', [sa.text("to_tsvector('english'::regconfig, document_title::text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_language', 'documents', ['document_language'], unique=False)
    op.create_index('ix_documents_creation_date', 'documents', ['document_creation_date'], unique=False)
    op.create_index('ix_documents_author', 'documents', ['document_author'], unique=False)
    op.alter_column('documents', 'document_modification_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Document last modification date (from metadata)',
               existing_nullable=True)
    op.alter_column('documents', 'document_creation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Document creation date (from metadata)',
               existing_nullable=True)
    op.alter_column('documents', 'document_language',
               existing_type=sa.VARCHAR(length=10),
               comment='Detected language (ISO 639-1 code)',
               existing_nullable=True)
    op.alter_column('documents', 'document_keywords',
               existing_type=sa.TEXT(),
               comment='Extracted keywords (comma-separated)',
               existing_nullable=True)
    op.alter_column('documents', 'document_subject',
               existing_type=sa.VARCHAR(length=500),
               comment='Extracted document subject/description',
               existing_nullable=True)
    op.alter_column('documents', 'document_author',
               existing_type=sa.VARCHAR(length=200),
               comment='Extracted document author',
               existing_nullable=True)
    op.alter_column('documents', 'document_title',
               existing_type=sa.VARCHAR(length=500),
               comment='Extracted document title',
               existing_nullable=True)
    op.create_table_comment(
        'answer_feedback',
        'Tracks answer quality metrics and user feedback',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_answer_feedback_user_rating'), table_name='answer_feedback')
    op.drop_index(op.f('ix_answer_feedback_user_id'), table_name='answer_feedback')
    op.drop_index(op.f('ix_answer_feedback_session_id'), table_name='answer_feedback')
    op.drop_index(op.f('ix_answer_feedback_quality_level'), table_name='answer_feedback')
    op.drop_index(op.f('ix_answer_feedback_overall_score'), table_name='answer_feedback')
    op.drop_index(op.f('ix_answer_feedback_message_id'), table_name='answer_feedback')
    op.drop_index(op.f('ix_answer_feedback_created_at'), table_name='answer_feedback')
    op.drop_index('ix_feedback_user_rating', table_name='answer_feedback')
    op.create_index('ix_feedback_user_rating', 'answer_feedback', ['user_rating'], unique=False)
    op.drop_index('ix_feedback_quality_level', table_name='answer_feedback')
    op.create_index('ix_feedback_quality_level', 'answer_feedback', ['quality_level'], unique=False)
    op.create_index('ix_feedback_session_id', 'answer_feedback', ['session_id'], unique=False)
    op.create_index('ix_feedback_rating_created', 'answer_feedback', ['user_rating', 'created_at'], unique=False)
    op.create_index('ix_feedback_quality_created', 'answer_feedback', ['quality_level', 'created_at'], unique=False)
    op.create_index('ix_feedback_overall_score', 'answer_feedback', ['overall_score'], unique=False)
    op.alter_column('answer_feedback', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('answer_feedback', 'suggestions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('answer_feedback', 'quality_level',
               existing_type=sa.VARCHAR(length=20),
               comment='Quality level: excellent, good, acceptable, poor, very_poor',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'user_rating',
               existing_type=sa.INTEGER(),
               comment='User feedback: 1=good, 0=neutral, -1=bad',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'hallucination_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Risk of hallucination (0-1, higher = more risk)',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'grounding_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='How well answer is grounded in sources (0-1)',
               existing_nullable=True)
    op.alter_column('answer_feedback', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Overall quality score (0-1)',
               existing_nullable=False)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='groups_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    sa.UniqueConstraint('name', name='groups_name_key'),
    comment='User groups for permission management',
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_groups_name', 'groups', ['name'], unique=False)
    op.create_index('ix_groups_created_by', 'groups', ['created_by'], unique=False)
    op.create_table('document_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('granted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('permission_type', postgresql.ENUM('read', 'write', 'admin', name='permission_type'), server_default=sa.text("'read'::permission_type"), autoincrement=False, nullable=False, comment='Permission level: read < write < admin'),
    sa.Column('granted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Optional expiration timestamp for temporary permissions'),
    sa.CheckConstraint('user_id IS NOT NULL AND group_id IS NULL OR user_id IS NULL AND group_id IS NOT NULL', name='check_user_or_group'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_permissions_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name='document_permissions_granted_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='document_permissions_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='document_permissions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_permissions_pkey'),
    sa.UniqueConstraint('document_id', 'group_id', name='uq_document_group_permission'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_user_permission'),
    comment='Document access control permissions'
    )
    op.create_index('ix_document_permissions_user', 'document_permissions', ['user_id'], unique=False)
    op.create_index('ix_document_permissions_group', 'document_permissions', ['group_id'], unique=False)
    op.create_index('ix_document_permissions_expires', 'document_permissions', ['expires_at'], unique=False)
    op.create_index('ix_document_permissions_document', 'document_permissions', ['document_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False, comment='The query text submitted by user'),
    sa.Column('query_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Query execution mode (fast, balanced, deep)'),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Response time in milliseconds'),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Confidence score of the response (0-1)'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional metadata (search type, complexity, etc.)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='query_logs_pkey'),
    comment='Query execution logs for monitoring and analytics'
    )
    op.create_index('ix_query_logs_query_mode', 'query_logs', ['query_mode'], unique=False)
    op.create_index('ix_query_logs_created_at', 'query_logs', ['created_at'], unique=False)
    op.create_index('ix_query_logs_confidence_score', 'query_logs', ['confidence_score'], unique=False)
    op.create_table('system_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Unique configuration key'),
    sa.Column('config_value', sa.TEXT(), autoincrement=False, nullable=False, comment='Configuration value (stored as text)'),
    sa.Column('config_type', sa.VARCHAR(length=50), server_default=sa.text("'string'::character varying"), autoincrement=False, nullable=False, comment='Data type of the value'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Human-readable description'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_config_pkey'),
    sa.UniqueConstraint('config_key', name='system_config_config_key_key'),
    comment='System-wide configuration storage'
    )
    op.create_index('idx_system_config_key', 'system_config', ['config_key'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('feedback_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mode_used', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='feedback_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False)
    op.create_index('ix_feedback_message_id', 'feedback', ['message_id'], unique=False)
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name='group_members_added_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='group_members_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='group_members_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='group_members_pkey'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user_membership'),
    comment='Group membership relationships'
    )
    op.create_index('ix_group_members_user', 'group_members', ['user_id'], unique=False)
    op.create_index('ix_group_members_group', 'group_members', ['group_id'], unique=False)
    op.create_table('embedding_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunking_strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('embedding_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_stats_pkey'),
    comment='Embedding generation statistics'
    )
    op.create_index('idx_embedding_model', 'embedding_stats', ['embedding_model'], unique=False)
    op.create_index('idx_embedding_document_id', 'embedding_stats', ['document_id'], unique=False)
    op.create_index('idx_embedding_created', 'embedding_stats', ['created_at'], unique=False)
    op.create_table('migration_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migration_history_pkey'),
    sa.UniqueConstraint('filename', name='migration_history_filename_key')
    )
    op.create_table('daily_accuracy_trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_queries', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avg_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high_confidence_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_token_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='daily_accuracy_trends_pkey'),
    sa.UniqueConstraint('date', name='daily_accuracy_trends_date_key'),
    comment='Daily aggregated accuracy and performance trends'
    )
    op.create_index('idx_daily_trend_date', 'daily_accuracy_trends', ['date'], unique=False)
    op.create_table('hybrid_search_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('search_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('results_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hybrid_search_stats_pkey'),
    comment='Hybrid search statistics'
    )
    op.create_index('idx_search_session_id', 'hybrid_search_stats', ['session_id'], unique=False)
    op.create_index('idx_search_created_type', 'hybrid_search_stats', ['created_at', 'search_type'], unique=False)
    op.create_index('idx_search_created', 'hybrid_search_stats', ['created_at'], unique=False)
    op.create_index('idx_search_cache', 'hybrid_search_stats', ['cache_hit'], unique=False)
    op.create_table('rag_processing_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('query_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('complexity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rag_processing_stats_pkey'),
    comment='RAG processing statistics with quality metrics'
    )
    op.create_index('idx_rag_success', 'rag_processing_stats', ['success'], unique=False)
    op.create_index('idx_rag_session_id', 'rag_processing_stats', ['session_id'], unique=False)
    op.create_index('idx_rag_created_mode', 'rag_processing_stats', ['created_at', 'mode'], unique=False)
    op.create_index('idx_rag_created', 'rag_processing_stats', ['created_at'], unique=False)
    op.create_index('idx_rag_complexity', 'rag_processing_stats', ['complexity'], unique=False)
    op.create_table('file_upload_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size_mb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('processing_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='file_upload_stats_pkey'),
    comment='File upload statistics for monitoring'
    )
    op.create_index('idx_file_upload_type', 'file_upload_stats', ['file_type'], unique=False)
    op.create_index('idx_file_upload_file_id', 'file_upload_stats', ['file_id'], unique=False)
    op.create_index('idx_file_upload_created_status', 'file_upload_stats', ['created_at', 'status'], unique=False)
    op.create_index('idx_file_upload_created', 'file_upload_stats', ['created_at'], unique=False)
    op.drop_index(op.f('ix_execution_steps_timestamp'), table_name='execution_steps')
    op.drop_index('ix_execution_steps_execution_timestamp', table_name='execution_steps')
    op.drop_index('ix_execution_steps_execution_number', table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_execution_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_execution_metrics_execution_id'), table_name='execution_metrics')
    op.drop_table('execution_metrics')
    op.drop_index('ix_workflow_subflows_workflow_type', table_name='workflow_subflows')
    op.drop_index(op.f('ix_workflow_subflows_workflow_id'), table_name='workflow_subflows')
    op.drop_index(op.f('ix_workflow_subflows_subflow_type'), table_name='workflow_subflows')
    op.drop_index(op.f('ix_workflow_subflows_parent_block_id'), table_name='workflow_subflows')
    op.drop_index('ix_workflow_subflows_parent_block', table_name='workflow_subflows')
    op.drop_table('workflow_subflows')
    op.drop_index(op.f('ix_workflow_edges_workflow_id'), table_name='workflow_edges')
    op.drop_index(op.f('ix_workflow_edges_target_node_id'), table_name='workflow_edges')
    op.drop_index(op.f('ix_workflow_edges_source_node_id'), table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_execution_schedules_user_id'), table_name='execution_schedules')
    op.drop_index(op.f('ix_execution_schedules_next_execution_at'), table_name='execution_schedules')
    op.drop_index('ix_execution_schedules_next_execution', table_name='execution_schedules')
    op.drop_index(op.f('ix_execution_schedules_is_active'), table_name='execution_schedules')
    op.drop_index(op.f('ix_execution_schedules_agent_id'), table_name='execution_schedules')
    op.drop_index('ix_execution_schedules_agent_active', table_name='execution_schedules')
    op.drop_table('execution_schedules')
    op.drop_index(op.f('ix_agent_versions_created_at'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_index('ix_agent_versions_agent_created', table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_agent_tools_tool_id'), table_name='agent_tools')
    op.drop_index('ix_agent_tools_agent_order', table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_agent_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_agent_knowledgebases_knowledgebase_id'), table_name='agent_knowledgebases')
    op.drop_index(op.f('ix_agent_knowledgebases_agent_id'), table_name='agent_knowledgebases')
    op.drop_index('ix_agent_kb_agent_priority', table_name='agent_knowledgebases')
    op.drop_table('agent_knowledgebases')
    op.drop_index('ix_agent_executions_user_status', table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_user_id'), table_name='agent_executions')
    op.drop_index('ix_agent_executions_status_started', table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_started_at'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_session_id'), table_name='agent_executions')
    op.drop_index('ix_agent_executions_agent_started', table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_agent_edges_workflow_id'), table_name='agent_edges')
    op.drop_index('ix_agent_edges_workflow', table_name='agent_edges')
    op.drop_index(op.f('ix_agent_edges_target_block_id'), table_name='agent_edges')
    op.drop_index('ix_agent_edges_target', table_name='agent_edges')
    op.drop_index(op.f('ix_agent_edges_source_block_id'), table_name='agent_edges')
    op.drop_index('ix_agent_edges_source', table_name='agent_edges')
    op.drop_table('agent_edges')
    op.drop_index(op.f('ix_workflow_webhooks_workflow_id'), table_name='workflow_webhooks')
    op.drop_index('ix_workflow_webhooks_workflow_active', table_name='workflow_webhooks')
    op.drop_index(op.f('ix_workflow_webhooks_webhook_path'), table_name='workflow_webhooks')
    op.drop_index(op.f('ix_workflow_webhooks_is_active'), table_name='workflow_webhooks')
    op.drop_table('workflow_webhooks')
    op.drop_index(op.f('ix_workflow_schedules_workflow_id'), table_name='workflow_schedules')
    op.drop_index('ix_workflow_schedules_workflow_active', table_name='workflow_schedules')
    op.drop_index(op.f('ix_workflow_schedules_next_execution_at'), table_name='workflow_schedules')
    op.drop_index('ix_workflow_schedules_next_execution', table_name='workflow_schedules')
    op.drop_index(op.f('ix_workflow_schedules_is_active'), table_name='workflow_schedules')
    op.drop_table('workflow_schedules')
    op.drop_index(op.f('ix_workflow_nodes_workflow_id'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index('ix_workflow_executions_workflow_started', table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index('ix_workflow_executions_user_status', table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_user_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_session_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_prompt_template_versions_prompt_template_id'), table_name='prompt_template_versions')
    op.drop_table('prompt_template_versions')
    op.drop_index(op.f('ix_knowledgebase_versions_knowledgebase_id'), table_name='knowledgebase_versions')
    op.drop_index(op.f('ix_knowledgebase_versions_created_at'), table_name='knowledgebase_versions')
    op.drop_index('ix_kb_versions_kb_created', table_name='knowledgebase_versions')
    op.drop_table('knowledgebase_versions')
    op.drop_index(op.f('ix_knowledgebase_documents_knowledgebase_id'), table_name='knowledgebase_documents')
    op.drop_index(op.f('ix_knowledgebase_documents_document_id'), table_name='knowledgebase_documents')
    op.drop_table('knowledgebase_documents')
    op.drop_index(op.f('ix_block_versions_created_at'), table_name='block_versions')
    op.drop_index(op.f('ix_block_versions_block_id'), table_name='block_versions')
    op.drop_index('ix_block_versions_block_created', table_name='block_versions')
    op.drop_table('block_versions')
    op.drop_index(op.f('ix_block_test_cases_block_id'), table_name='block_test_cases')
    op.drop_table('block_test_cases')
    op.drop_index(op.f('ix_block_dependencies_parent_block_id'), table_name='block_dependencies')
    op.drop_index(op.f('ix_block_dependencies_child_block_id'), table_name='block_dependencies')
    op.drop_table('block_dependencies')
    op.drop_index('ix_agents_user_type', table_name='agents')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index('ix_agents_user_created', table_name='agents')
    op.drop_index(op.f('ix_agents_is_public'), table_name='agents')
    op.drop_index(op.f('ix_agents_deleted_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_agent_blocks_workflow_type', table_name='agent_blocks')
    op.drop_index(op.f('ix_agent_blocks_workflow_id'), table_name='agent_blocks')
    op.drop_index('ix_agent_blocks_workflow_enabled', table_name='agent_blocks')
    op.drop_index(op.f('ix_agent_blocks_type'), table_name='agent_blocks')
    op.drop_table('agent_blocks')
    op.drop_index('ix_workflows_user_public', table_name='workflows')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_is_public'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_secrets_variable_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_resource_shares_share_token'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_resource_type'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_resource_id'), table_name='resource_shares')
    op.drop_index('ix_resource_shares_resource', table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_expires_at'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_created_by'), table_name='resource_shares')
    op.drop_table('resource_shares')
    op.drop_index(op.f('ix_prompt_templates_is_system'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index('ix_permissions_user_resource', table_name='permissions')
    op.drop_index(op.f('ix_permissions_user_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource_type'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource_id'), table_name='permissions')
    op.drop_index('ix_permissions_resource', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_knowledgebases_user_id'), table_name='knowledgebases')
    op.drop_index(op.f('ix_knowledgebases_milvus_collection_name'), table_name='knowledgebases')
    op.drop_index(op.f('ix_knowledgebases_created_at'), table_name='knowledgebases')
    op.drop_table('knowledgebases')
    op.drop_index('ix_blocks_user_type', table_name='blocks')
    op.drop_index('ix_blocks_user_public', table_name='blocks')
    op.drop_index(op.f('ix_blocks_user_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_is_public'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_type'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index('ix_audit_logs_user_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_variables_scope_id'), table_name='variables')
    op.drop_index(op.f('ix_variables_scope'), table_name='variables')
    op.drop_index(op.f('ix_variables_name'), table_name='variables')
    op.drop_index(op.f('ix_variables_is_secret'), table_name='variables')
    op.drop_index(op.f('ix_variables_deleted_at'), table_name='variables')
    op.drop_table('variables')
    op.drop_index(op.f('ix_tools_is_builtin'), table_name='tools')
    op.drop_index(op.f('ix_tools_category'), table_name='tools')
    op.drop_table('tools')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_oauth_credentials_user_id'), table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_tool_id'), table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_agent_templates_is_published'), table_name='agent_templates')
    op.drop_index(op.f('ix_agent_templates_category'), table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
